demo_password: ''

cassandra_password: 'VendekDam4'
cassandra_data_dir: '/data/cassandra'
cassandra_replication_factor: 1
cassandra_seed_nodes: '172.31.24.66'
cassandra_nodes: ['172.31.24.66']

nginx_listen_address: '52.29.12.61'

malt_admin_host: '172.31.24.66'

config:
  "ip-172-31-24-66":
    cassandra_listen_address: '172.31.24.66'
    cassandra_rmi_host: '172.31.24.66'
    malt_engine_rmi_host: '172.31.24.66'
    malt_engine_host: '172.31.24.66'

malt_engine_config:
  "cache-on": true
  "port": 3000
  "host": "{{config[ansible_hostname].malt_engine_host}}"
  "session-ttl": 900
  "storage-keyspace": malt
  "storage-nodes": "{{cassandra_nodes}}"
  "storage-password": "{{cassandra_password}}"
  "storage-user": malt
  "monitoring-hostname": "{{ansible_nodename}}"
  "zabbix-host": null
  "zabbix-port": 10051
  "noilly-port": 1300

malt_admin_config:
  "host": "{{malt_admin_host}}"
  "port": 8080
  "api-addr": "{{nginx_listen_address}}/api"
  "app-env": "production"
  "noilly-port": 1301
  "session-ttl": 3600
  "settings-table": "settings"
  "offload-repo": null
  "storage-keyspace": malt
  "storage-nodes": "{{cassandra_nodes}}"
  "storage-password": "{{cassandra_password}}"
  "storage-user": malt
  "monitoring-hostname": "{{ansible_nodename}}"
  "zabbix-host": null
  "zabbix-port": 10051


malt_engine_jmx_port: 7198

cassandra_jmx_port: 7199
cassandra_max_heap_size: '2500m'
cassandra_new_heap_size: '1g'
cassandra_max_new_size: '625m'

malt_engine_heap_size: '2500m'
malt_admin_heap_size: '1g'

git_ref: stable