cassandra_password: 'SoHoorain6'
cassandra_data_dir: '/data/cassandra'
cassandra_replication_factor: 2
cassandra_seed_nodes: "{% for host in groups.tag_CassandraSeed_Yes %}{{ hostvars[host].ec2_private_ip_address }}{% if not loop.last %},{% endif %}{% endfor %}"
cassandra_nodes: ['172.31.22.122', '172.31.22.123', '172.31.22.124']

nginx_listen_address: '{{hostvars[groups.tag_Nginx_Yes[0]].ec2_private_ip_address}}'

malt_admin_host: '{{hostvars[groups.tag_MaltAdmin_Yes[0]].ec2_private_ip_address}}'

config:
  "ip-172-31-22-122":
    cassandra_listen_address: '172.31.22.122'
    cassandra_rmi_host: '172.31.22.122'
    malt_engine_rmi_host: '172.31.22.122'
    malt_engine_host: '172.31.22.122'

  "ip-172-31-22-123":
    cassandra_listen_address: '172.31.22.123'
    cassandra_rmi_host: '172.31.22.123'
    malt_engine_rmi_host: '172.31.22.123'
    malt_engine_host: '172.31.22.123'

  "ip-172-31-22-124":
    cassandra_listen_address: '172.31.22.124'
    cassandra_rmi_host: '172.31.22.124'
    malt_engine_rmi_host: '172.31.22.124'
    malt_engine_host: '172.31.22.124'

malt_engine_config:
  "cache-on": true
  "port": 3000
  "host": "{{config[ansible_hostname].malt_engine_host}}"
  "session-ttl": 900
  "storage-keyspace": malt
  "storage-nodes": "{{cassandra_nodes}}"
  "storage-password": "{{cassandra_password}}"
  "storage-user": malt
  "monitoring-hostname": "{{ansible_nodename}}"
  "zabbix-host": null
  "zabbix-port": 10051
  "noilly-port": 1300

malt_admin_config:
  "host": "{{malt_admin_host}}"
  "port": 8080
  "api-addr": "{{nginx_listen_address}}/api"
  "app-env": "production"
  "noilly-port": 1301
  "session-ttl": 3600
  "settings-table": "settings"
  "offload-repo": null
  "storage-keyspace": malt
  "storage-nodes": "{{cassandra_nodes}}"
  "storage-password": "{{cassandra_password}}"
  "storage-user": malt
  "monitoring-hostname": "{{ansible_nodename}}"
  "zabbix-host": null
  "zabbix-port": 10051


malt_engine_jmx_port: 7198

cassandra_jmx_port: 7199
cassandra_max_heap_size: '5g'
cassandra_new_heap_size: '2g'
cassandra_max_new_size: '1250m'

malt_engine_heap_size: '5g'
malt_admin_heap_size: '2g'

git_ref: stable