- name: "Set up admin"
  hosts: admin
  tasks:
    - name: Install packets
      yum: pkg="{{item}}" state=installed
      with_items:
        - wget
        - git
      sudo: yes

    - name: Download oracle jdk 7
      command: >
        wget --no-cookies --no-check-certificate -c
        --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
        "http://download.oracle.com/otn-pub/java/jdk/7u71-b14/jdk-7u71-linux-x64.tar.gz"
      args:
        chdir: "{{ansible_env.HOME}}"

    - name: Extract jdk
      command: tar xzf jdk-7u71-linux-x64.tar.gz

    - name: Set default java binaries
      command: "alternatives --install /usr/bin/{{item}} {{item}} {{ansible_env.HOME}}/jdk1.7.0_71/bin/{{item}} 1"
      sudo: yes
      with_items:
        - java
        - jdk
        - jar

    - name: Clone project
      git: repo="gitolite@bagira.favoritbet.com:malt_admin"
           dest="{{ansible_env.HOME}}/malt_admin"
           accept_hostkey=True
