- name: Bulid MathAdmin release
  hosts: ci
  roles: [ci]
  tasks:
    - name: Print version
      debug: msg="NEW VERSION STRING {{ math_admin_version | mandatory }}"

    - name: Create keys dir
      file: path=.ssh state=directory

    - name: Copy Keys
      copy: src="roles/malt_admin/files/keys/{{item}}"
            dest=".ssh/{{item}}"
            mode="600"
      with_items:
        - math_admin
        - math_admin.pub

    - name: Clone project
      git: repo=git@github.com:TicTacLab/math_admin.git
           key_file=.ssh/math_admin
           force=yes
           dest=math_admin
           update=yes
           version="{{git_ref}}"
           accept_hostkey=yes
      register: project

    - name: Install npm packages
      npm: path=math_admin/node_modules state=present

    - name: Clean dir
      shell: lein clean && grunt clean
      environment:
        LEIN_USERNAME: admin
        LEIN_PASSWORD: NeOpBac8
      args:
        chdir: math_admin

    - name: Build assets
      command: grunt build
      args:
        chdir: math_admin

    - name: Build Uberjar
      command: lein uberjar
      environment:
        LEIN_USERNAME: admin
        LEIN_PASSWORD: NeOpBac8
      args:
        chdir: math_admin

    - name: Bump version
      replace: dest=math_admin/project.clj
               regexp='^(\(defproject malt_admin ).*$'
               replace='\1"{{math_admin_version | mandatory}}"'

    - name: Create dist dir
      file: path="{{item}}" state=directory
      with_items:
        - dist/math_admin-{{ math_admin_version }}
        - dist/math_admin-{{ math_admin_version }}/conf
        - dist/math_admin-{{ math_admin_version }}/bin
        - dist/math_admin-{{ math_admin_version }}/lib

    - name: Copy config.json
      command: >
        cp math_admin/config.example.json
           dist/math_admin-{{ math_admin_version }}/conf/config.json

    - name: Copy logger-conf.xml
      command: >
        cp math_admin/resources/logback.production.xml
           dist/math_admin-{{ math_admin_version }}/conf/logger-conf.xml

    - name: Copy executable script
      copy: src=roles/common/files/math_admin.sh
            dest=dist/math_admin-{{ math_admin_version }}/bin/math_admin.sh
            mode='a+x'

    - name: Copy jar
      command: >
        cp math_admin/target/math_admin_standalone.jar
           dist/math_admin-{{ math_admin_version }}/lib/math_admin.jar

    - name: Clean old zip dist
      file: path="dist/math_admin-{{ math_admin_version }}.zip" state=absent

    - name: Zip dist
      command: zip -r math_admin-{{ math_admin_version }}.zip math_admin-{{ math_admin_version }}
      args:
        chdir: dist

    - name: PUT dist to S3
      command: >
        aws s3 cp --region eu-central-1
         dist/math_admin-{{ math_admin_version }}.zip
         s3://com.betengines.releases/math_admin/math_admin-{{ math_admin_version }}.zip
      environment:
          AWS_ACCESS_KEY_ID: "{{access_key}}"
          AWS_SECRET_ACCESS_KEY: "{{secret_key}}"
