- name: Update Malt Engine
  hosts: tag_Demo1_Yes:&tag_MaltEngine_Yes
  serial: 1
  tasks:

    - name: Clone project
      git: repo=git@github.com:TicTacLab/math_engine.git
           key_file=.ssh/math_engine
           force=yes
           dest=new_malt_engine
           update=yes
           version="{{git_ref}}"
           accept_hostkey=yes
      register: project

    - name: Replace logback.xml
      command: mv resources/logback.production.xml resources/logback.xml
      args: { chdir: new_malt_engine }

    - name: Write config
      copy: dest=new_malt_engine/config.json
            content="{{malt_engine_config|to_json|safe}}"

    - name: Stop Service
      service: name=malt_engine state=stopped
      sudo: yes

    - name: Remove old dir
      command: rm -rf malt_engine
      sudo: yes

    - name: Move to the latest version
      command: mv new_malt_engine malt_engine
      sudo: yes

    - name: Start Service
      service: name=malt_engine state=started
      sudo: yes

    - name: Wait for service to start
      wait_for: port="{{malt_engine_config.port}}" host="{{config[ansible_hostname].malt_engine_host}}" state=present
