- name: Setup Malt Admin
  hosts: malt_admin
  tasks:
    - include: common/tasks/oracle_jdk.yml
    - include: common/tasks/lein.yml
    - include: common/tasks/build_utils.yml
    - include: common/tasks/copy_keys.yml

    - name: Copy service file
      template: src=malt_admin/templates/malt_admin.service dest=/etc/systemd/system/malt_admin.service
      sudo: yes
      register: service_file

    - name: Reload service file in systemd
      command: systemctl daemon-reload
      sudo: yes
      when: service_file|changed

    - name: Set autostart
      service: name=malt_admin enabled=yes
      sudo: yes

    - name: Create malt admin dir
      file: path=malt_admin state=directory

