- name: Setup Cassandra
  hosts: cassandra
  tasks:
    - include: common/tasks/oracle_jdk.yml

    - name: Add datastax.repo
      copy: src=cassandra/files/datastax.repo dest=/etc/yum.repos.d/datastax.repo
      sudo: yes

    - name: Install Cassandra
      yum: name=dsc20 state=installed
      sudo: yes

    - name: Copy cassandra.yaml
      template: src=cassandra/templates/cassandra.yaml dest=/etc/cassandra/conf/cassandra.yaml
      sudo: yes

    - name: Run Cassandra
      service: name=cassandra state=restarted
      sudo: yes

    - name: User exists?
      command: cqlsh -u malt -p {{cassandra_password}} -e "LIST USERS" {{groups.cassandra[0]}}
      register: user_check

    - name: Create malt user
      shell: >
        cqlsh -u cassandra -p cassandra -e "CREATE USER malt WITH PASSWORD '{{cassandra_password}}' SUPERUSER"  {{groups.cassandra[0]}} &&
        cqlsh -u malt -p {{cassandra_password}} -e "ALTER USER cassandra WITH PASSWORD 'vedCucokvod7' NOSUPERUSER" {{groups.cassandra[0]}}
      when: user_check|failed

    - name: Copy schema files
      copy: src=cassandra/templates/schema dest=/tmp

    - name: Copy schema settings files
      template: src=cassandra/templates/schema/settings.cql dest=/tmp/schema/settings.cql

    - name: Initialize schema
      shell: >
        cqlsh -u malt -p {{cassandra_password}} -f /tmp/schema/keyspace.cql  {{groups.cassandra[0]}} &&
        cqlsh -u malt -p {{cassandra_password}} -f /tmp/schema/schema.cql -k malt  {{groups.cassandra[0]}} &&
        cqlsh -u malt -p {{cassandra_password}} -f /tmp/schema/config.cql -k malt  {{groups.cassandra[0]}} &&
        cqlsh -u malt -p {{cassandra_password}} -f /tmp/schema/settings.cql -k malt  {{groups.cassandra[0]}}
