- name: Setup Cassandra
  hosts: cassandra
  tasks:
    - include: common/tasks/oracle_jdk.yml

    - name: Add datastax.repo
      copy: src=cassandra/files/datastax.repo dest=/etc/yum.repos.d/datastax.repo
      sudo: yes

    - name: Install Cassandra
      yum: name=dsc20 state=installed
      sudo: yes

    - name: Copy cassandra.yaml
      template: src=cassandra/templates/cassandra.yaml dest=/etc/cassandra/conf/cassandra.yaml
      sudo: yes

    - name: Remove cassandra data dir
      shell: rm -rf {{cassandra_data_dir}}/*
      sudo: yes 

    - name: Create cassandra data dir
      file: path={{cassandra_data_dir}}} state=directory owner=cassandra
      sudo: yes

    - name: Move old logs
      command: mv /var/log/cassandra/system.log /var/log/cassandra/system.log.old
      sudo: yes
      ignore_errors: yes

    - name: Run Cassandra
      service: name=cassandra state=restarted
      sudo: yes

    - name: Wait for Cassandra to start
      wait_for: host=/var/log/cassandra/system.log timeout=20 search_regex='.*Listening for thrift clients.*' state=present

- name: Load data
  hosts: cassandra[0]
  tasks:
    - name: User exists?
      command: cqlsh -u malt -p {{cassandra_password}} -e "LIST USERS" {{groups.cassandra[0]}}
      register: user_check
      ignore_errors: yes

    - name: Create malt user
      shell: >
        cqlsh -u cassandra -p cassandra -e "CREATE USER malt WITH PASSWORD '{{cassandra_password}}' SUPERUSER"  {{groups.cassandra[0]}} &&
        cqlsh -u malt -p {{cassandra_password}} -e "ALTER USER cassandra WITH PASSWORD 'vedCucokvod7' NOSUPERUSER" {{groups.cassandra[0]}}
      when: user_check|failed

    - name: Copy schema files
      copy: src=cassandra/templates/schema dest=/tmp

    - name: Copy schema settings files
      template: src=cassandra/templates/schema/settings.cql dest=/tmp/schema/settings.cql

    - name: Copy schema configuration files
      template: src=cassandra/templates/schema/config.cql dest=/tmp/schema/config.cql

    - name: Initialize schema
      shell: >
        cqlsh -u malt -p {{cassandra_password}} -f /tmp/schema/keyspace.cql  {{groups.cassandra[0]}} &&
        cqlsh -u malt -p {{cassandra_password}} -f /tmp/schema/schema.cql -k malt  {{groups.cassandra[0]}} &&
        cqlsh -u malt -p {{cassandra_password}} -f /tmp/schema/config.cql -k malt  {{groups.cassandra[0]}} &&
        cqlsh -u malt -p {{cassandra_password}} -f /tmp/schema/settings.cql -k malt  {{groups.cassandra[0]}}
