- name: Setup Malt Engine
  hosts: tag_MaltEngine_Yes
  serial: 3
  tasks:
    - include: common/tasks/oracle_jdk.yml
    - include: common/tasks/lein.yml
    - include: common/tasks/maven.yml
    - include: common/tasks/build_utils.yml
    - include: common/tasks/copy_keys.yml

    - name: Install ant
      yum: name=ant state=installed
      sudo: yes

    - name: Copy service file
      template: src=malt_engine/templates/malt_engine.service dest=/etc/systemd/system/malt_engine.service
      sudo: yes
      register: service_file

    - name: Reload service file in systemd
      command: systemctl daemon-reload
      sudo: yes
      when: service_file|changed

    - name: Set autotstart
      service: name=malt_engine enabled=yes
      sudo: yes

    - include: common/tasks/poi.yml
      when: rebuild_poi|default(false)
