- name: Setup Malt Engine
  hosts: tag_MaltEngine_Yes
  serial: 3
  tasks:
    - include: common/tasks/oracle_jdk.yml
    - include: common/tasks/lein.yml
    - include: common/tasks/maven.yml
    - include: common/tasks/build_utils.yml

    - name: Create keys dir
      file: path=.ssh state=directory
    
    - name: Copy Keys
      copy: src="malt_engine/files/keys/{{item}}" dest=".ssh/{{item}}" mode="600"
      with_items:
        - math_engine
        - math_engine.pub

    - name: Install ant
      apt: name=ant state=installed
      sudo: yes
      when: rebuild_poi|default(false)

    - name: Copy service file
      template: src=malt_engine/templates/malt_engine.upstart.conf dest=/etc/init/malt_engine.conf
      sudo: yes

    - name: Set autotstart
      service: name=malt_engine enabled=yes
      sudo: yes

    - include: common/tasks/poi.yml
      when: rebuild_poi|default(false)
