- include: disable_selinux.yml
#- include: aws_memory_monitoring.yml
- include: pre_cassandra.yml
- include: pre_malt_admin.yml
- include: update_malt_admin.yml
- include: pre_malt_engine.yml
- include: update_malt_engine.yml
- include: pre_nginx.yml
