- name: Update Malt Engine
  hosts: malt_engine
  tasks:

    - name: Clone project
      git: repo=gitolite@git.favorit:malt_engine
           dest=new_malt_engine
           update=yes
           version="{{git_ref}}"
           accept_hostkey=yes
      register: project

    - name: Stop Service
      service: name=malt_engine state=stopped
      sudo: yes

    - name: Remove old dir
      command: rm -rf malt_engine
      sudo: yes

    - name: Move to the latest version
      command: mv new_malt_engine malt_engine
      sudo: yes

    - name: Start Service
      service: name=malt_engine state=started
      sudo: yes