- name: Update Malt Admin
  hosts: malt_admin
  tasks:
    - name: Stop Service
      service: name=malt_admin state=stopped
      sudo: yes

    - name: Clone project
      git: repo=gitolite@git.favorit:malt_admin
           dest=malt_admin
           update=yes
           version="{{git_ref}}"
           accept_hostkey=yes
      register: project

    - stat: path=malt_admin/target/malt-admin-standalone.jar
      register: jar

    - name: Build proto files
      command: lein protobuf
      args:
        chdir: malt_admin
      when: project.changed or not jar.stat.exists

    - name: Cleanup target
      file: path=malt_admin/target state=absent
      when: project.changed or not jar.stat.exists

    - name: Make jar file
      command: lein uberjar
      args:
        chdir: malt_admin
      when: project.changed or not jar.stat.exists

    - name: Start Service
      service: name=malt_admin state=started
      sudo: yes
