- name: Update Malt Admin
  hosts: malt_admin
  tasks:

    - name: Clone project
      git: repo=gitolite@git.favorit:malt_admin
           dest=new_malt_admin
           update=yes
           version="{{git_ref}}"
           accept_hostkey=yes
      register: project

    - name: Stop Service
      service: name=malt_admin state=stopped
      sudo: yes

    - name: Remove old dir
      command: rm -rf malt_admin
      sudo: yes

    - name: Move to the latest version
      command: mv new_malt_admin malt_admin
      sudo: yes

    - name: Start Service
      service: name=malt_admin state=started
      sudo: yes
