- name: Install nodejs
  apt: name="{{item}}" state=installed
  with_items:
   - nodejs
   - npm
  sudo: yes

- name: Create symlink
  file: src=/usr/bin/nodejs
        dest=/usr/bin/node
        state=link
  sudo: yes

- name: Install grunt-cli
  npm: name=grunt-cli global=yes state=present
  sudo: yes