- name: Add key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
  sudo: yes

- name: Add repository
  apt_repository: repo="{{item}}" state=present
  with_items:
    - 'deb http://nginx.org/packages/ubuntu/ trusty nginx'
    - 'deb-src http://nginx.org/packages/ubuntu/ trusty nginx'
  sudo: yes

- name: Install nginx
  apt: name=nginx state=installed update_cache=yes
  sudo: yes