- name: Copy default config
  template: src=default.conf.j2 dest=/etc/nginx/nginx.conf
  sudo: yes

- name: Mkdir config dir
  file: path=/etc/nginx/conf state=directory owner=nginx group=nginx mode=0775
  sudo: yes

- name: Mkdir docroot dir
  file: path=/var/www/error state=directory owner=nginx group=nginx mode=0775
  sudo: yes

- name: Mkdir img dir
  file: path=/var/www/error/img state=directory owner=nginx group=nginx mode=0775
  sudo: yes

- name: Mkdir css dir
  file: path=/var/www/error/css state=directory owner=nginx group=nginx mode=0775
  sudo: yes

- name: Copy Under Constraction page
  copy: src=error503.html dest=/var/www/error owner=nginx group=nginx mode=0775
  sudo: yes

- name: Copy Under Constraction page style
  copy: src=landing-page.css dest=/var/www/error/css/ owner=nginx group=nginx mode=0775
  sudo: yes

- name: Copy Under Constraction page background
  copy: src=intro-bg.jpg dest=/var/www/error/img/ owner=nginx group=nginx mode=0775
  sudo: yes

- name: Copy Under Construction bootstrap
  copy: src=bootstrap.min.css dest=/var/www/error/css/ owner=nginx group=nginx mode=0775
  sudo: yes